# Algoritmo programado sem Funções do Numpy

### Funções para gerar matriz e produto

In [18]:
import numpy as np 

In [19]:
# Gerador de Matriz aleatória
def gerador():
  matriz = []
  for i in range(5):
    temp = []
    for i in range(5):
      rand = np.random.randint(9)
      temp.append(rand)
    matriz.append(temp)
    temp = []
  return matriz  

# Transforma Matriz B na transposta de B
def transposta(m_b):
  aux = []
  for i in range(len(m_b)):
    temp = []
    for j in range(len(m_b)):
      pos2 = m_b[j]
      temp.append(pos2[i])
    aux.append(temp)
  return aux

# Multiplicação das matrizes
# m_a e m_aux sao variaveis locais para Matriz A e Matriz aux (Matriz B transposta)
def multiplicacao(m_a,m_aux):
  prod = []
  for i in range(len(m_a)):
    temp = []
    pos1 = m_a[i]
    c = 0
    for j in range(len(m_aux)):
      pos2 = m_aux[j]
      for k in range(len(m_aux)):
        c += (pos1[k]*pos2[k])
      temp.append(c)
      c = 0
    prod.append(temp)
  return prod

### Algoritmo

In [20]:
matriz_a = gerador()
matriz_b = gerador()
matriz_aux = transposta(matriz_b)
multi = multiplicacao(matriz_a,matriz_aux)

print('Matriz A')
print(np.array(matriz_a))
print('\nMatriz B')
print(np.array(matriz_b))
print('\nProduto')
print(np.array(multi))

Matriz A
[[6 2 3 6 3]
 [0 6 7 5 5]
 [1 2 7 6 0]
 [0 0 1 8 8]
 [3 2 4 5 4]]

Matriz B
[[2 4 4 7 5]
 [5 4 2 1 5]
 [7 0 3 6 7]
 [0 2 7 1 8]
 [2 5 5 3 2]]

Produto
[[ 49  59  94  77 115]
 [ 89  59  93  68 129]
 [ 61  24  71  57 112]
 [ 23  56  99  38  87]
 [ 52  50  83  64 101]]


# Algoritmo programado com Funções do Numpy

In [21]:
matriz_a = np.random.randint(9, size=(5, 5)) 
matriz_b = np.random.randint(9, size=(5, 5))
multi = np.matmul(matriz_a,matriz_b)

In [22]:
print('Matriz A')
print(matriz_a)
print('\nMatriz B')
print(matriz_b)
print('\nProduto')
print(multi)

Matriz A
[[7 7 2 3 0]
 [3 6 5 0 2]
 [8 7 8 8 8]
 [3 6 3 5 7]
 [8 6 2 7 2]]

Matriz B
[[8 8 3 3 7]
 [7 3 1 2 2]
 [6 8 3 0 2]
 [2 1 3 2 8]
 [7 7 4 8 4]]

Produto
[[123  96  43  41  91]
 [110  96  38  37  51]
 [233 213 111 118 182]
 [143 120  67  87 107]
 [146 119  65  66 136]]
